### ISSUE TITLE
It stops working when we define variable within template

### ISSUE THREAD

**Issue by ezhlobo** [ezhlobo/eslint-plugin-react-pug#57]
For example this code will break eslint:

```jsx
pug`
  - const test = 'test'
`
```

The error message is not useful, but stacktrace reveals that babel doesn't like it and doesn't want to parse:

```
Unexpected token (1:1)
SyntaxError: Unexpected token (1:1)
  at Parser.raise (~/node_modules/@babel/parser/lib/index.js:4028:15)
  at Parser.unexpected (~/node_modules/@babel/parser/lib/index.js:5343:16)
  at Parser.parseExprAtom (~/node_modules/@babel/parser/lib/index.js:6432:20)
  at Parser.parseExprSubscripts (~/node_modules/@babel/parser/lib/index.js:6019:21)
  at Parser.parseMaybeUnary (~/node_modules/@babel/parser/lib/index.js:5998:21)
  at Parser.parseExprOps (~/node_modules/@babel/parser/lib/index.js:5907:21)
  at Parser.parseMaybeConditional (~/node_modules/@babel/parser/lib/index.js:5879:21)
  at Parser.parseMaybeAssign (~/node_modules/@babel/parser/lib/index.js:5826:21)
  at Parser.parseParenAndDistinguishExpression (~/node_modules/@babel/parser/lib/index.js:6588:28)
  at Parser.parseExprAtom (~/node_modules/@babel/parser/lib/index.js:6388:21)
```

**Comment by ezhlobo** [comment]
Fixed in [v0.5.7](https://github.com/ezhlobo/eslint-plugin-react-pug/releases/tag/v0.5.7)
