### ISSUE TITLE
v0.0.5: Cannot find module './lib/rules/uses-react'

### ISSUE THREAD

**Issue by bbruneau** [ezhlobo/eslint-plugin-react-pug#9]
Hi @ezhlobo,

Thanks for the response on my template literals issue. I updated to 0.0.5 and trying to lint a file with nested literals, but I got this error:

```
✖ jsLinter found some errors. Please fix them and try committing again.

Cannot find module './lib/rules/uses-react'
Error: Cannot find module './lib/rules/uses-react'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/deploy/projects/node_modules/eslint-plugin-react-pug/index.js:8:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

Listing the contents of `eslint-plugin-react-pug/lib` shows it's empty.

**Comment by ezhlobo** [comment]
@bbruneau hi, sorry for noticing this. After publishing a new package to NPM did not pull it to my own project so I missed this.

The problem was that `yarn publish` which I used missed some files during packaging. That is why it can't find `lib/*.js` files.

I've just republished it through npm (found a workaround in [yarn/issues](https://github.com/yarnpkg/yarn/issues)).

So please, try version `0.0.6`. Works well for me.

**Comment by bbruneau** [comment]
🙏 many thanks, works a charm!
